### ISSUE TITLE
Make repo name truncation configurable

### ISSUE THREAD

**Issue by jlec** [dlvhdr/gh-dash#217]
The repo name is truncated at a hard 18 chars

https://github.com/dlvhdr/gh-dash/blob/d89be39ea4a8d930ee6f8e33eaa0cd982e758006/ui/components/pr/pr.go#LL143C64-L143C66

I do have a lot of repo starting with `ansible-..` or `terraform-...`. To properly understand which repo we are talking about I would need more chars. Could we make this configurable?

**Comment by robdimsdale** [comment]
@dlvhdr Can I ask if there is value in continuing to support truncation on repository names. As someone who often interacts with repositories that have long names, I actually prefer to increase column width and disable truncation (by modifying the code and rebuilding). And I can't find an easy way to make this configurable (see details below).

I have to assume that most users who interact with repository names longer than the hard-coded limit of 18 characters would prefer to remove truncation altogether. And users with repository names less than the hard-coded limit are unaffected either way.

I am happy to submit a PR that removes truncation altogether, if that's the direction you are willing to go in.

### Configuring truncation length

If there is value in truncating the repo name, then I think it's actually quite tricky to make this configurable. Taking `PRs` as an example (though the same logic applies to `issues` too) - the truncation happens when creating the contents [here](https://github.com/dlvhdr/gh-dash/blob/0b1a3eaa5291f046b32d9e6a34c4e442c5f683d0/ui/components/pr/pr.go#L143) - before the `TextStyle` is applied and the cell is rendered. But there is currently no mechanism to provide the column width at this point. The column width is not calculated until the entire table is rendered [here](https://github.com/dlvhdr/gh-dash/blob/0b1a3eaa5291f046b32d9e6a34c4e442c5f683d0/ui/components/table/table.go#L218) - after the row is created and the `TextStyle` applied.

I explored truncating the text at this point that the table is rendered but it does not work as expected due to the text styling adding extra characters. And there is no obvious way to remove the text styling, truncate the contents, and re-add the text styling. The number of characters added by styling isn't consistent, so we can't just add an offset when truncating. And we can't "undo" the styling, because it's just a string.

### Commit history for truncation

It looks like truncation used to be present for other fields - specifically title and author. But truncation for those fields was removed in [this commit](https://github.com/dlvhdr/gh-dash/commit/b1ef660a8cbd267d175a041c80d0d04628f9e0a3) - leaving only truncation for repo name. It's not clear why truncation was removed for these other fields but kept for repo name.

Additional commit history:
* [This commit](https://github.com/dlvhdr/gh-dash/commit/9f7a454f9f26fd443e26a51be34dc97677de27af) added truncation was for title, author, and repository name.
* [This commit](https://github.com/dlvhdr/gh-dash/commit/7a8918cb2790e7bf12f963bd18a93845a25fe9e0) removed truncation for title but kept it for author and repo name.
* [This commit](https://github.com/dlvhdr/gh-dash/commit/49b27c70a6b3b30ab71b72f09b4786e16f231c16) re-added truncation for title.

**Comment by dlvhdr** [comment]
Hi @robdimsdale, appreciate the discussion.
I'm not quite sure why I decided on the 18 character limit, I think it just made sense prior to adding configuration to allow columns to stretch etc. It probably what worked for the repos I worked with.

Anyway this isn't the ideal solution of course and I'd very much appreciate a contribution that gets rid of this :)
Possible solutions are:
1. Just delete the limit
2. Delete the limit and add a `grow: true` by default on repo names headers (which users can override with their `config.yml`.
3. In addition, add the repo owner + name to the preview pane which has more vertical space to fully display these values.

The calculation for how to distribute the available horizontal space is [here](https://github.com/dlvhdr/gh-dash/blob/0b1a3eaa5291f046b32d9e6a34c4e442c5f683d0/ui/components/table/table.go#L161)

If I'm not mistaken, it first calculates how many terminal columns the non growing columns take, and then distributes the rest among the growing columns.

**Comment by robdimsdale** [comment]
This makes sense to me. I think option 2 (which includes option 1) is an easy win and I'd like to start there. Just wanted to make sure I wasn't missing some context about truncating names.

I'm happy to explore the third idea as well. I think it's valuable. If it's easy, I'm happy to include it in the PR that removes the truncation. If it's more complex then I think I'll open a separate issue.

**Comment by dlvhdr** [comment]
Cool, so without `grow=true`, how does that look? Can you add a screenshot?

**Comment by robdimsdale** [comment]
Given that #224 was merged, can we close this issue?
