### ISSUE TITLE
[BUG] dash should not list issues of archived repositories

### ISSUE THREAD

**Issue by robdimsdale** [dlvhdr/gh-dash#221]
**Describe the bug**

Similar to #124 but for issues instead of PRs. Currently issues on archived repositories are shown, despite the fact that users generally can't interact with issues on archived repositories. Users cannot close issues, comment on them, etc.

I'm happy to submit a PR to address this if we agree we should filter out issues from archived repositories.

**To Reproduce**
1. run `gh dash` with some config which will fetch issues of an archived repository (e.g. https://github.com/paketo-buildpacks/stacks)
2. observe that archived issues are visible

**Expected behavior**
I expect that issues from archived repositories are not shown.

**Screenshots**

Here is an archived repo, showing open issues:

<img width="941" alt="Screen Shot 2023-01-16 at 3 49 10 PM" src="https://user-images.githubusercontent.com/7230694/212763476-0033d883-0477-4969-b832-8dd848bb05f4.png">

And just to demonstrate that this repository is archived:

<img width="478" alt="Screen Shot 2023-01-16 at 3 49 33 PM" src="https://user-images.githubusercontent.com/7230694/212763526-2d728acc-37de-4990-94fb-1405ae2f94ef.png">

**Desktop (please complete the following information):**
 - OS: Mac

**Comment by dlvhdr** [comment]
Yes this is tech debt I want handled. Currently the code between prs and issues is a bit duplicated with the original thought to merge once needed. Since I didn't find the time, some features were only implemented in one place.
[Here's the code for prs.](https://github.com/dlvhdr/gh-dash/blob/0b1a3eaa5291f046b32d9e6a34c4e442c5f683d0/ui/components/prssection/prssection.go#L273)

**Comment by robdimsdale** [comment]
@dlvhdr I think this is good to close now, yes? Unless you'd prefer to keep the issue open to drive out a refactor?
