### ISSUE TITLE
[BUG] `open in GitHub` with Chrome opened, corrupts UI

### ISSUE THREAD

**Issue by SamWolfs** [dlvhdr/gh-dash#410]
**Describe the bug**
When Chrome (or FireFox) is opened and I open a PR using `open in GitHub`, an information message is shown in the terminal `Opening in existing browser session`. This shifts the UI by 1 line, corrupting the UI until the application is restarted.

**To Reproduce**

1. Go to any PR.
2. Click `o` to open the PR in GitHub.
3. A message should appear, notifying the user that the existing browser session was used.

**Expected behavior**
The informational message should not be shown, so the UI doesn't break.

**Screenshots**

![image](https://github.com/user-attachments/assets/e0b4490e-f5c4-4e3a-b8a6-fe445b89e842)

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Comment by jamestrew** [comment]
I'm still experiencing this issue on the nightly build.
I've done some debugging and found the cause of the issue for me. 
The mechanism for opening the link has a few paths depending on 
  1. `GH_BROWSER` env var set
  2. browser key in ~/.config/gh/config.yml
  3. `BROWSER` env var
  4. Falls back to `cliBrowser.OpenURL()` (my case)

And in the `cliBrowser.OpenURL()` code, they hardcode the stdout/stderr paths. https://github.com/cli/browser/blob/b393df5d7bfa7490b76669e04a8652c3e167c524/browser.go#L14-L18
And since I'm on linux and have xdg-open, this gets used and the xdg-open output just gets dumped on the screen.

So the workaround is to set any of the 3 browser settings. Even a simple `GH_BROWSER=xdg-open` fixes the issue. 
Would love to a fix in dash itself but I recognize the issue stems from deep in the dependencies, would be tricky without some hack or non-trivial change.

**Comment by lulzhipsters** [comment]
Still happening, I set `BROWSER: nohup xdg-open` in my gh config to workaround
